# Generated by Django 4.0.3 on 2022-04-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='respuest_text',
            new_name='respuesta_text',
        ),
    ]
